# Site settings
name: Logesh Kumar Umapathi
title: Logesh Kumar Umapathi | Data Scientist
description: Data Scientist specializing in NLP and Deep learning
url: https://logeshumapathi.com/
baseurl: ""
email: logeshkumaru@gmail.com
cover: https://logeshumapathi.com/img/og.png
logo: https://logeshumapathi.com/img/emojis/male-technologist.png
resume: https://logeshumapathi.com/resume.pdf
social:
  - title: email
    url: mailto:logeshkumaru@gmail.com
  - title: twitter
    url: https://twitter.com/logesh_umapathi/
  - title: instagram
    url: https://www.instagram.com/madeinmadras_/
  - title: github
    url: https://github.com/infinitylogesh/
  - title: linkedin
    url: https://www.linkedin.com/in/logeshkumaru/

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
